# Database Properties
spring.datasource.username=${qualidnd-spring-datasource-username}
spring.datasource.password=${qualidnd-spring-datasource-password}
spring.datasource.url=${qualidnd-spring-datasource-url}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
spring.jpa.open-in-view=false

# Logging Properties
logging.level.root=INFO

# Server Properties
server.error.whitelabel.enabled=false
server.error.include-stacktrace=never
server.error.include-exception=false
server.port=${PORT:8080}
spring.profiles.active=dev

# Max file size.
spring.servlet.multipart.max-file-size=65MB
# Max request size.
spring.servlet.multipart.max-request-size=80MB


# Azure Keyvault
azure.keyvault.enabled=true
azure.keyvault.uri=${qualidnd.key.vault.uri}
azure.keyvault.client-id=${qualidnd.key.vault.client.id}
azure.keyvault.client-key=${qualidnd.key.vault.client.key}
azure.keyvault.tenant-id=${qualidnd.key.vault.tenant.id}

# Redis info
spring.redis.host=${qualidnd-redis-host}
spring.redis.port=${qualidnd-redis-port}
spring.redis.password=${qualidnd-redis-password}

# Redis Repository and JdbcTemplate fix
spring.main.allow-bean-definition-overriding=true 